spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
  freemarker:
    cache: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false